jobs:
  mvn-test-macos-aarch64:
    name: mvn test on Apple M1
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Cache dependencies
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        architecture: arm
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
    strategy:
      fail-fast: false
  mvn-test-x86:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Cache dependencies
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1.4.3
      with:
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - '8'
        - '11'
        os:
        - ubuntu-latest
        - macos-latest
        - - self-hosted
          - macos
          - aarch64
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
